
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Oct 17 2021 21:27:08 IST (Oct 17 2021 15:57:08 UTC)

// Verification Directory fv/mod8 

module mod8(clk, rst, out);
  input clk, rst;
  output [2:0] out;
  wire clk, rst;
  wire [2:0] out;
  wire n_0, n_1, n_2, n_3;
  DFQZRM2RA \out_reg[2] (.CK (clk), .D (n_0), .RB (out[0]), .Q
       (out[2]));
  DFQZRM2RA \out_reg[1] (.CK (clk), .D (n_3), .RB (n_2), .Q (out[1]));
  MXB2M1RA g115(.A (n_1), .B (out[0]), .S (out[1]), .Z (n_2));
  AN2M2R g114(.A (n_3), .B (out[1]), .Z (n_0));
  NR2B1M2R g116(.B (out[2]), .NA (rst), .Z (n_3));
  DFZRM2RA \out_reg[0] (.CK (clk), .D (n_3), .RB (n_1), .Q (out[0]),
       .QB (n_1));
endmodule

